//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonFE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddonFE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_Actualizar_FELFolioPrefNumFactAnt&quot; 
        ///(
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN TipoDoc varchar(10)
        ///) 
        ///LANGUAGE SQLSCRIPT 
        ///AS 
        ///BEGIN
        ///	DECLARE SP_SerieNameOINV,SP_SerieNameODPI,FolioPref varchar(15);
        ///	declare SP_FolioNumOINV,SP_FolioNumODPI,FolioNum INTEGER;
        ///
        ///	FolioNum:=0;
        ///	
        ///	--OBTENIENDO LA SERIE
        ///	SELECT T1.&quot;SeriesName&quot; into SP_SerieNameODPI FROM &quot;ODPI&quot; T0 
        ///	INNER JOIN &quot;NNM1&quot; T1 ON T0.&quot;Series&quot;=T1.&quot;Series&quot;
        ///	WHERE T0.&quot;DocEntry&quot;=DocEntry;
        ///	
        ///	SELECT SUBSTRING(SP_SerieNameODPI, 1, 4) [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_Actualizar_FELFolioPrefNumFactAnt {
            get {
                return ResourceManager.GetString("SMC_Actualizar_FELFolioPrefNumFactAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_Actualizar_FELFolioPrefNumGUIA&quot; 
        ///(
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN TipoDoc varchar(10)
        ///) 
        ///LANGUAGE SQLSCRIPT 
        ///AS 
        ///BEGIN
        ///	DECLARE SP_SerieNameODLN,SP_SerieNameOWTR,SP_SerieNameOIGE,SP_SerieNameORPD,FolioPref varchar(15) DEFAULT &apos;&apos;;
        ///	declare SP_FolioNumODLN,SP_FolioNumOWTR,SP_FolioNumOIGE,SP_FolioNumORPD,FolioNum INTEGER DEFAULT 0;
        ///	create local temporary table #TablaDatos (
        ///		&quot;CORRELATIVO&quot; INTEGER);
        ///	FolioNum:=0;
        ///	
        ///	--OBTENIENDO LA SERIE
        ///	 IF ObjectType=&apos;15&apos; THEN 
        ///		SP_ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_Actualizar_FELFolioPrefNumGUIA {
            get {
                return ResourceManager.GetString("SMC_Actualizar_FELFolioPrefNumGUIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_Actualizar_FELFolioPrefNumOINV&quot; 
        ///(
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN TipoDoc varchar(10)
        ///) 
        ///LANGUAGE SQLSCRIPT 
        ///AS 
        ///BEGIN
        ///	DECLARE SP_SerieNameOINV,SP_SerieNameODPI,FolioPref varchar(15);
        ///	declare SP_FolioNumOINV,SP_FolioNumODPI,FolioNum INTEGER;
        ///
        ///	FolioNum:=0;
        ///	
        ///	--OBTENIENDO LA SERIE
        ///	SELECT T1.&quot;SeriesName&quot; into SP_SerieNameOINV FROM &quot;OINV&quot; T0 
        ///	INNER JOIN &quot;NNM1&quot; T1 ON T0.&quot;Series&quot;=T1.&quot;Series&quot;
        ///	WHERE T0.&quot;DocEntry&quot;=DocEntry;
        ///	
        ///	SELECT SUBSTRING(SP_Seri [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_Actualizar_FELFolioPrefNumOINV {
            get {
                return ResourceManager.GetString("SMC_Actualizar_FELFolioPrefNumOINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_Actualizar_FELFolioPrefNumORIN&quot; 
        ///(
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN TipoDoc varchar(10)
        ///) 
        ///LANGUAGE SQLSCRIPT 
        ///AS 
        ///BEGIN
        ///	DECLARE SP_SerieNameORIN,FolioPref varchar(15);
        ///	declare SP_FolioNumORIN,FolioNum INTEGER;
        ///
        ///	FolioNum:=0;
        ///	
        ///	--OBTENIENDO LA SERIE
        ///	SELECT T1.&quot;SeriesName&quot; into SP_SerieNameORIN FROM &quot;ORIN&quot; T0 
        ///	INNER JOIN &quot;NNM1&quot; T1 ON T0.&quot;Series&quot;=T1.&quot;Series&quot;
        ///	WHERE T0.&quot;DocEntry&quot;=DocEntry;
        ///	
        ///	SELECT SUBSTRING(SP_SerieNameORIN, 1, 4) into FolioPref 
        ///	FROM DUMMY;
        ///	--OBT [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_Actualizar_FELFolioPrefNumORIN {
            get {
                return ResourceManager.GetString("SMC_Actualizar_FELFolioPrefNumORIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_ActualizarEstadoFE&quot; 
        ///(
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN MensajeError varchar(150),
        ///	IN Estado varchar(150)
        ///) 
        ///LANGUAGE SQLSCRIPT 
        ///AS 
        ///BEGIN
        ///	DECLARE EstadoFE VARCHAR(10);
        ///	
        ///	SELECT 
        ///	(CASE 
        ///		WHEN Estado=&apos;AC_03&apos; THEN &apos;02&apos;
        ///		WHEN Estado=&apos;RC_05&apos; THEN &apos;03&apos;
        ///		WHEN Estado=&apos;PE_02&apos; THEN &apos;01&apos;
        ///		WHEN Estado=&apos;01&apos; THEN &apos;01&apos;
        ///		ELSE &apos;00&apos;
        ///	 END )into  EstadoFE
        ///	FROM dummy;
        ///	
        ///	IF ObjectType=&apos;13&apos; THEN
        ///		UPDATE &quot;OINV&quot; SET 
        ///		&quot;U_SMC_MSJ_ESTADO_FE&quot;=MensajeError,
        ///		&quot;U_SMC_ESTADO_FE&quot;=Estado [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_ActualizarEstadoFE {
            get {
                return ResourceManager.GetString("SMC_ActualizarEstadoFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_ANULACION_OINV_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN
        ///	SELECT
        ///	T3.&quot;GlblLocNum&quot; as numeroDocumentoEmisor,
        ///	&apos;1.0&apos; as version,
        ///	&apos;2.0&apos; as versionUBL,
        ///	&apos;6&apos; as tipoDocumentoEmisor,
        ///	
        ///	&apos;RA-&apos;||TO_VARCHAR(T0.&quot;U_SMC_FECHABAJA&quot; ,&apos;yyyyMMdd&apos;)
        ///	||&apos;-&apos;
        ///	||LPAD((select count(*) from &quot;OINV&quot; where &quot;U_SMC_FECHABAJA&quot; = TO_VARCHAR(T0.&quot;U_SMC_FECHABAJA&quot; ,&apos;yyyyMMdd&apos;) and &quot;U_SMC_ESTADO_FE&quot; = &apos;04&apos;)+1 ,3,&apos;0&apos;) 
        ///	as resumenId,
        ///	
        ///	TO_VARCHAR(T0.&quot;TaxDate&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_ANULACION_OINV_FE {
            get {
                return ResourceManager.GetString("SMC_ANULACION_OINV_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_ANULACION_OINV_FE_ACTUALIZAR&quot; 
        ///(
        ///	IN DocEntry INT
        ///) 
        ///LANGUAGE SQLSCRIPT 
        ///AS 
        ///BEGIN
        ///	
        ///	UPDATE OINV
        ///	SET &quot;U_SMC_MSJ_ESTADO_FE&quot;=&apos;SU DOCUMENTO HA SIDO DADO DE BAJA&apos;,
        ///	&quot;U_SMC_ESTADO_FE&quot;=&apos;04&apos;
        ///	WHERE &quot;DocEntry&quot;=DocEntry;	
        ///END;.
        /// </summary>
        internal static string SMC_ANULACION_OINV_FE_ACTUALIZAR {
            get {
                return ResourceManager.GetString("SMC_ANULACION_OINV_FE_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_ANULACION_OVPM_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	SELECT
        ///	T3.&quot;GlblLocNum&quot; as numeroDocumentoEmisor,
        ///	&apos;1.0&apos; as version,
        ///	&apos;2.0&apos; as versionUBL,
        ///	&apos;6&apos; as tipoDocumentoEmisor,
        ///	&apos;RA-&apos;||TO_VARCHAR(CURRENT_DATE ,&apos;yyyyMMdd&apos;)||&apos;-001&apos; as resumenId,
        ///	TO_VARCHAR(CURRENT_DATE ,&apos;yyyy-MM-dd&apos;) as fechaEmisionComprobante,
        ///	TO_VARCHAR(CURRENT_DATE ,&apos;yyyy-MM-dd&apos;) as fechaGeneracionResumen,
        ///	T3.&quot;BPLName&quot; as razonSocialEmisor,
        ///	&apos;-&apos; as correoEmisor,
        ///	1 as in [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_ANULACION_OVPM_FE {
            get {
                return ResourceManager.GetString("SMC_ANULACION_OVPM_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTE_DETALLE_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	DECLARE SP_CODIMPUESTO VARCHAR(10);
        ///	DECLARE SP_MONTO DECIMAL(18,6);
        ///	
        ///
        ///	create local temporary table #TablaDatos (
        ///	&quot;NUMEROORDENITEM&quot; varchar(10),
        ///	&quot;UNIDADMEDIDA&quot; varchar(10),
        ///	&quot;CANTIDAD&quot; decimal(18,6),
        ///	&quot;CODIGOPRODUCTO&quot; varchar(25),
        ///	&quot;CODIGOPRODUCTOSUNAT&quot; varchar(25),
        ///	&quot;DESCRIPCION&quot; varchar(100),
        ///	&quot;IMPORTEUNITARIOSINIMPUESTO&quot; decimal(18,6),
        ///	&quot;IMPORTEUNITARIOCO [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTE_DETALLE_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTE_DETALLE_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTE_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///
        ///	DECLARE ExisteDetraccion INT DEFAULT 0;
        ///	DECLARE SP_CODIMPUESTO,SP_SERIENUM_GUIA VARCHAR(10);
        ///	DECLARE SP_MONTO,SP_OPERACIONESGRAVADA,SP_OPERACIONESGRAVADAGRAT,SP_OPERACIONESEXONERADA,SP_OPERACIONESNOGRAVADAS,SP_MONTOANTICIPO,SP_TOTALESANTICIPO DECIMAL(18,6);
        ///
        ///	SELECT TOP 1
        ///	ifnull((T1.&quot;Price&quot;),0),&quot;TaxCode&quot;,
        ///	(CASE 
        ///		WHEN T0.&quot;DocCur&quot;=&apos;SOL&apos; THEN T0.&quot;DpmAmnt&quot; ELSE T0.&quot;DpmAm [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTE_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTE_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTECUOTAS_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///		DECLARE MontoDescuentoPEN decimal(18,2);
        ///	DECLARE MontoDescuentoUSD decimal(18,2);
        ///	
        ///	
        ///	SELECT 
        ///		(SUM(S0.&quot;InsTotal&quot;)-SUM(S0.&quot;WTSum&quot;)) into MontoDescuentoPEN
        ///		FROM INV6 S0 WHERE  S0.&quot;DocEntry&quot; =:DocEntry  and UPPER(IFNULL(S0.&quot;U_EXX_CONFTIPODET&quot;,&apos;NO&apos;)) = &apos;NO&apos;;
        ///	--FROM INV6 S0 WHERE  S0.&quot;DocEntry&quot; =:DocEntry  and UPPER(IFNULL(&apos;NO&apos;,&apos;NO&apos;)) = &apos;NO&apos;;	
        ///	SELECT 
        ///		(SUM(S0.&quot;InsTotalFC&quot;)-SUM [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTECUOTAS_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTECUOTAS_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTECUOTASODPI_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///		DECLARE MontoDescuentoPEN decimal(18,2);
        ///	DECLARE MontoDescuentoUSD decimal(18,2);
        ///	
        ///	
        ///	SELECT 
        ///		(SUM(S0.&quot;InsTotal&quot;)-SUM(S0.&quot;WTSum&quot;)) into MontoDescuentoPEN
        ///		FROM INV6 S0 WHERE  S0.&quot;DocEntry&quot; =:DocEntry  and UPPER(IFNULL(S0.&quot;U_EXX_CONFTIPODET&quot;,&apos;NO&apos;)) = &apos;NO&apos;;
        ///	--FROM INV6 S0 WHERE  S0.&quot;DocEntry&quot; =:DocEntry  and UPPER(IFNULL(&apos;NO&apos;,&apos;NO&apos;)) = &apos;NO&apos;;	
        ///	SELECT 
        ///		(SUM(S0.&quot;InsTotalFC&quot;) [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTECUOTASODPI_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTECUOTASODPI_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTENC_DETALLE_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	DECLARE SP_CODIMPUESTO VARCHAR(10);
        ///	DECLARE SP_MONTO DECIMAL(18,6);
        ///	
        ///	
        ///	create local temporary table #TablaDatos (
        ///	&quot;numeroOrdenItem&quot; varchar(10),
        ///	&quot;unidadMedida&quot; varchar(10),
        ///	&quot;cantidad&quot; decimal(18,6),
        ///	&quot;codigoProducto&quot; varchar(10),
        ///	&quot;codigoProductoSUNAT&quot; varchar(10),
        ///	&quot;descripcion&quot; varchar(100),
        ///	&quot;importeUnitarioSinImpuesto&quot; decimal(18,6),
        ///	&quot;importeUnitarioConImpuesto&quot; decim [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTENC_DETALLE_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTENC_DETALLE_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTENC_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	
        ///	DECLARE ExisteDetraccion INT DEFAULT 0;
        ///	DECLARE SP_CODIMPUESTO VARCHAR(10);
        ///	DECLARE SP_MONTO,SP_OPERACIONESGRAVADA,SP_OPERACIONESNOGRAVADAS DECIMAL(18,6);
        ///	
        ///	SELECT TOP 1
        ///	(T1.&quot;Price&quot;),&quot;TaxCode&quot; into SP_MONTO,SP_CODIMPUESTO
        ///	FROM &quot;ORIN&quot; T0
        ///	INNER JOIN &quot;RIN1&quot; T1 ON T0.&quot;DocEntry&quot;=T1.&quot;DocEntry&quot;
        ///	WHERE T0.&quot;DocEntry&quot;=:DocEntry;
        ///	
        ///	
        ///	--HALLANDO TOTALES
        ///	SELECT 
        ///	SUM(T [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTENC_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTENC_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTEODPI_DETALLE_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	DECLARE SP_CODIMPUESTO VARCHAR(10);
        ///	DECLARE SP_MONTO DECIMAL(18,6);
        ///	
        ///
        ///	create local temporary table #TablaDatos (
        ///	&quot;NUMEROORDENITEM&quot; varchar(10),
        ///	&quot;UNIDADMEDIDA&quot; varchar(10),
        ///	&quot;CANTIDAD&quot; decimal(10,6),
        ///	&quot;CODIGOPRODUCTO&quot; varchar(10),
        ///	&quot;CODIGOPRODUCTOSUNAT&quot; varchar(10),
        ///	&quot;DESCRIPCION&quot; varchar(100),
        ///	&quot;IMPORTEUNITARIOSINIMPUESTO&quot; decimal(18,6),
        ///	&quot;IMPORTEUNITAR [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTEODPI_DETALLE_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTEODPI_DETALLE_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_COMPROBANTEODPI_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	
        ///	DECLARE ExisteDetraccion INT DEFAULT 0;
        ///	DECLARE SP_CODIMPUESTO,SP_CODEDETRACCION VARCHAR(10) DEFAULT &apos;&apos;;
        ///	DECLARE SP_MONTO,SP_OPERACIONESGRAVADA,SP_OPERACIONESNOGRAVADAS,
        ///			SP_PORCENTAJEDETRACCION,SP_TOTALDETRACCION,
        ///			SP_MONTOTOTAL, TIPOCAMBIO DECIMAL(18,6);
        ///
        ///	SELECT TOP 1
        ///	(T1.&quot;Price&quot;),&quot;TaxCode&quot;,
        ///	(CASE 
        ///		WHEN T0.&quot;DocCur&quot;=&apos;SOL&apos; THEN T0.&quot;DocTotal&quot; ELSE T0.&quot;DocT [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTEODPI_FE {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTEODPI_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE procedure &quot;SMC_COMPROBANTES_ELECTRONICOS&quot;
        ///(
        ///	IN Fecha1 date,
        ///	IN fecha2 date,
        ///	IN tipodoc nvarchar(500),
        ///	IN estado nvarchar(5),
        ///	In sucursal varchar(10) default null
        ///) 
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN 
        ///
        ///	SELECT  * ,CURRENT_DATE FROM (
        ///	
        ///		SELECT comp.&quot;DocEntry&quot;,&quot;DocNum&quot;,cli.&quot;LicTradNum&quot;  as &quot;Ruc&quot;,comp.&quot;CardName&quot;,comp.&quot;DocCur&quot;,comp.&quot;TaxDate&quot;,comp.&quot;Indicator&quot; as Indicator,
        ///		case comp.&quot;Indicator&quot; when &apos;01&apos; then &apos;FACTURA&apos;
        ///		when &apos;03&apos; then &apos;BOLETA&apos;
        ///		when &apos;08&apos; then &apos;NOTA DEBITO&apos;
        ///		ELSE &apos;&apos; E [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTES_ELECTRONICOS {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTES_ELECTRONICOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE procedure &quot;SMC_COMPROBANTES_ELECTRONICOS_SERVICIO&quot;
        ///(
        ///	IN Fecha1 date,
        ///	IN fecha2 date,
        ///	IN tipodoc nvarchar(500),
        ///	IN estado nvarchar(5)
        ///) 
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN 
        ///
        ///	SELECT  * ,CURRENT_DATE FROM (
        ///	
        ///		SELECT comp.&quot;DocEntry&quot;,&quot;DocNum&quot;,cli.&quot;LicTradNum&quot;  as &quot;Ruc&quot;,comp.&quot;CardName&quot;,comp.&quot;DocCur&quot;,comp.&quot;TaxDate&quot;,comp.&quot;Indicator&quot; as Indicator,
        ///		case comp.&quot;Indicator&quot; when &apos;01&apos; then &apos;FACTURA&apos;
        ///		when &apos;03&apos; then &apos;BOLETA&apos;
        ///		when &apos;08&apos; then &apos;NOTA DEBITO&apos;
        ///		ELSE &apos;&apos; END AS &quot;TipoDocumento&quot;,
        ///		comp.&quot;Comments&quot;,
        ///		(ca [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_COMPROBANTES_ELECTRONICOS_SERVICIO {
            get {
                return ResourceManager.GetString("SMC_COMPROBANTES_ELECTRONICOS_SERVICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_LISTARANTICIPOS_OINV&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN
        ///	SELECT DISTINCT 
        ///	ENComprobante.&quot;DocEntry&quot;,
        ///	&apos;A&apos; as indicador,
        ///	&apos;&apos; as numeroOrdenAnticipo,
        ///	CAST( Round(
        ///		(CASE 
        ///			fact_adelanto.&quot;DocCur&quot; 
        ///			WHEN &apos;SOL&apos; THEN fact_adelanto.&quot;DocTotal&quot; 
        ///			ELSE fact_adelanto.&quot;DocTotalFC&quot;  END
        ///		), 2) AS decimal(18, 2)) 
        ///	AS &quot;totalPrepagadoAnticipo&quot;,
        ///	TO_VARCHAR(fact_adelanto.&quot;TaxDate&quot; ,&apos;yyyy-MM-dd&apos;) as &quot;fechaPago&quot;,
        ///	Rtrim(fact_adelanto.&quot;FolioPref&quot;, 4 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_LISTARANTICIPOS_OINV {
            get {
                return ResourceManager.GetString("SMC_LISTARANTICIPOS_OINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a create procedure SMC_OBTENER_SUCURSALES
        ///as begin
        ///
        ///select &quot;BPLId&quot;, &quot;BPLName&quot; from OBPL;
        ///
        ///end.
        /// </summary>
        internal static string SMC_OBTENER_SUCURSALES {
            get {
                return ResourceManager.GetString("SMC_OBTENER_SUCURSALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_ODLN_GRE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	SELECT
        ///	T3.&quot;GlblLocNum&quot; as idEmisor,
        ///	&apos;09&apos; as tipoDocumento,
        ///	T0.&quot;FolioPref&quot; as Serie,
        ///	T0.&quot;FolioNum&quot;  as Correlativo,
        ///	&apos;richard.tito@imagina.pe&apos; as correoEmisor,
        ///	&apos;richard.tito@imagina.pe&apos; as correoAdquiriente,
        ///	--LPAD(&apos;1&apos;,8,&apos;0&apos;)
        ///	ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VARCHAR(T0.&quot;FolioNum&quot;),&apos;&apos;),8,&apos;0&apos;) as serieNumeroGuia,
        ///   --ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnu [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_ODLN_GRE {
            get {
                return ResourceManager.GetString("SMC_ODLN_GRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_OIGE_GRE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	SELECT
        ///	T3.&quot;GlblLocNum&quot; as idEmisor,
        ///	&apos;09&apos; as tipoDocumento,
        ///	T0.&quot;FolioPref&quot; as Serie,
        ///	T0.&quot;FolioNum&quot;  as Correlativo,
        ///	&apos;jhuniors.ramos@smartcode.pe&apos; as correoEmisor,
        ///	&apos;jhuniors.ramos@smartcode.pe&apos; as correoAdquiriente,
        ///	--LPAD(&apos;1&apos;,8,&apos;0&apos;)
        ///	ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VARCHAR(T0.&quot;FolioNum&quot;),&apos;&apos;),8,&apos;0&apos;) as serieNumeroGuia,
        ///   --ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VA [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_OIGE_GRE {
            get {
                return ResourceManager.GetString("SMC_OIGE_GRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_OINV_GRE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	SELECT
        ///	T0.&quot;FolioPref&quot; as Serie,
        ///	T0.&quot;FolioNum&quot;  as Correlativo,
        ///	ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;||ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;) as serieNumeroGuia,
        ///	T0.&quot;TaxDate&quot; as fechaEmisionGuia,
        ///	T0.&quot;Indicator&quot; as tipoDocumentoGuia,
        ///	T0.&quot;Comments&quot; AS Observaciones,
        ///	
        ///	
        ///	--DATOS DEL REMITENTE--
        ///	&apos;&apos; as numeroDocumentoRemitente,
        ///	&apos;&apos; as tipoDocumentoRemitente,
        ///	&apos;&apos; as razonSocialRemitente,
        ///	&apos;&apos; as numeroAutorizacion [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_OINV_GRE {
            get {
                return ResourceManager.GetString("SMC_OINV_GRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_ORPD_GRE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	SELECT
        ///	T3.&quot;GlblLocNum&quot; as idEmisor,
        ///	&apos;09&apos; as tipoDocumento,
        ///	T0.&quot;FolioPref&quot; as Serie,
        ///	T0.&quot;FolioNum&quot;  as Correlativo,
        ///	&apos;jhuniors.ramos@smartcode.pe&apos; as correoEmisor,
        ///	&apos;jhuniors.ramos@smartcode.pe&apos; as correoAdquiriente,
        ///	--LPAD(&apos;1&apos;,8,&apos;0&apos;)
        ///	ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VARCHAR(T0.&quot;FolioNum&quot;),&apos;&apos;),8,&apos;0&apos;) as serieNumeroGuia,
        ///   --ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VA [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_ORPD_GRE {
            get {
                return ResourceManager.GetString("SMC_ORPD_GRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_OWTR_GRE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN
        ///	SELECT
        ///	T3.&quot;GlblLocNum&quot; as idEmisor,
        ///	&apos;09&apos; as tipoDocumento,
        ///	T0.&quot;FolioPref&quot; as Serie,
        ///	T0.&quot;FolioNum&quot;  as Correlativo,
        ///	&apos;jhuniors.ramos@smartcode.pe&apos; as correoEmisor,
        ///	&apos;jhuniors.ramos@smartcode.pe&apos; as correoAdquiriente,
        ///	--LPAD(&apos;1&apos;,8,&apos;0&apos;)
        ///	ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VARCHAR(T0.&quot;FolioNum&quot;),&apos;&apos;),8,&apos;0&apos;) as serieNumeroGuia,
        ///   --ifnull(T0.&quot;FolioPref&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VA [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_OWTR_GRE {
            get {
                return ResourceManager.GetString("SMC_OWTR_GRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_RETENCION_DETALLE_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN
        ///	DECLARE FechaPago DATE;
        ///	DECLARE TipoCambio DECIMAL;
        ///	
        ///	SELECT 
        ///	&quot;TaxDate&quot; into FechaPago
        ///	FROM &quot;OVPM&quot; T0 WHERE &quot;DocEntry&quot;=DocEntry;
        ///	
        ///	select &quot;Rate&quot; into TipoCambio FROM &quot;ORTT&quot; WHERE &quot;Currency&quot;=&apos;USD&apos; and &quot;RateDate&quot;=FechaPago;
        ///	SELECT 
        ///	0 as numeroOrdenItem,
        ///	--ifnull(T4.&quot;FolioPref&quot;,&apos;&apos;)
        ///	&apos;F001&apos;||&apos;-&apos;|| LPAD(ifnull(TO_VARCHAR(T4.&quot;FolioNum&quot;),&apos;&apos;),8,&apos;0&apos;) as numeroDocument [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_RETENCION_DETALLE_FE {
            get {
                return ResourceManager.GetString("SMC_RETENCION_DETALLE_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_RETENCION_FE&quot;
        ///(
        ///	IN DocEntry INT	-- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN
        ///
        ///	SELECT 
        ///	T3.&quot;GlblLocNum&quot; as idEmisor,
        ///	20 as tipoDocumento,
        ///	T0.&quot;U_SMC_SERIE_FE&quot; as Serie,
        ///	T0.&quot;U_SMC_NUM_FE&quot;  as Correlativo,
        ///	&apos;richard.tito@imagina.pe&apos; as correoEmisor,
        ///	T2.&quot;E_Mail&quot; as correoAdquiriente,
        ///	
        ///	
        ///	ifnull(T0.&quot;U_SMC_SERIE_FE&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VARCHAR(T0.&quot;U_SMC_NUM_FE&quot;),&apos;&apos;),8,&apos;0&apos;) as serieNumeroRetencion,	
        ///	TO_VARCHAR(T0.&quot;TaxDate&quot;,&apos;yyyy-MM-dd&apos;) as fechaE [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_RETENCION_FE {
            get {
                return ResourceManager.GetString("SMC_RETENCION_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_Validar_FELFolioFactAnt&quot; 
        ///(
        ///	
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN TipoDoc varchar(10)
        ///) 
        ///AS 
        ///
        ///BEGIN 
        ///
        ///	SELECT IFNULL(&quot;FolioNum&quot;, &apos;0&apos;) AS &quot;FolioNum&quot; FROM &quot;ODPI&quot; WHERE 
        ///	&quot;Indicator&quot; = :TipoDoc AND &quot;DocEntry&quot; = :DocEntry 
        ///	AND &quot;ObjType&quot; = :ObjectType;
        ///END;.
        /// </summary>
        internal static string SMC_Validar_FELFolioFactAnt {
            get {
                return ResourceManager.GetString("SMC_Validar_FELFolioFactAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_Validar_FELFolioOINV&quot; 
        ///(
        ///	
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN TipoDoc varchar(10)
        ///) 
        ///AS 
        ///
        ///BEGIN 
        ///
        ///	SELECT IFNULL(&quot;FolioNum&quot;, &apos;0&apos;) AS &quot;FolioNum&quot; FROM &quot;OINV&quot; WHERE 
        ///	&quot;Indicator&quot; = :TipoDoc AND &quot;DocEntry&quot; = :DocEntry 
        ///	AND &quot;ObjType&quot; = :ObjectType;
        ///END;.
        /// </summary>
        internal static string SMC_Validar_FELFolioOINV {
            get {
                return ResourceManager.GetString("SMC_Validar_FELFolioOINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SMC_Validar_FELFolioORIN&quot; 
        ///(
        ///	
        ///	IN DocEntry INT,
        ///	IN ObjectType varchar(5),
        ///	IN TipoDoc varchar(10)
        ///) 
        ///AS 
        ///
        ///BEGIN 
        ///
        ///	SELECT IFNULL(&quot;FolioNum&quot;, &apos;0&apos;) AS &quot;FolioNum&quot; FROM &quot;ORIN&quot; WHERE 
        ///	&quot;Indicator&quot; = :TipoDoc AND &quot;DocEntry&quot; = :DocEntry 
        ///	AND &quot;ObjType&quot; = :ObjectType;
        ///END;.
        /// </summary>
        internal static string SMC_Validar_FELFolioORIN {
            get {
                return ResourceManager.GetString("SMC_Validar_FELFolioORIN", resourceCulture);
            }
        }
    }
}
